name: API CI

on:
  push:
    paths: ["api/**", ".github/workflows/api-ci.yml"]
  pull_request:
    paths: ["api/**"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/hr-api
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        working-directory: api
        run: dotnet restore

      - name: Build
        working-directory: api
        run: dotnet build -c Release --no-restore

      - name: Test
        if: ${{ hashFiles('**/*Tests*.csproj') != '' }}
        working-directory: api
        run: dotnet test -c Release --no-build

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
